# Addresse web du CNG où lire le HTML 
url_crf: url du crf
login: login
password: pasword
api_key: 273447AE2F7AE62F46A54C461727624F

# À modifier si les insturments de l'instance RedCap sont modifiés
# --
# Correspondance des champs barcode et redcap_repeated_instrument
# dans un résultat d'exportation de données via l'api redcap
type_barcode_to_instrument:
  germline_dna_cng_barcode: germline_dna_sequencing
  tumor_dna_barcode: tumor_dna_sequencing
  rna_cng_barcode: rna_sequencing
