version: 1

disable_existing_loggers: False

formatters:
  simple:
    format: "%(process)d :: %(asctime)s :: %(levelname)s :: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    maxBytes: 10485760  # 10MB
    backupCount: 20
    encoding: utf8

root:
  level: WARNING
  handlers: [console, file_handler]