mock_crf_data = {'couple_count': {('TEST_CHAMPS1', 'germline_dna_cng_barcode'): {'barcode': ['B00I1UK'],
                                                                 'count': 1},
                                  ('TEST_CHAMPS1', 'rna_cng_barcode'): {'barcode': ['B00I1VU'],
                                                                        'count': 1},
                                  ('TEST_CHAMPS1', 'tumor_dna_barcode'): {'barcode': ['B00I1UL'],
                                                                          'count': 1},
                                  ('TEST_CHAMPS2', 'tumor_dna_barcode'): {'barcode': ['B00I1UL'],
                                                                          'count': 1},
                                  ('TEST_CHAMPS3', 'rna_cng_barcode'): {'barcode': ['B00I1UL'],
                                                                        'count': 1},
                                  ('TEST_CHAMPS3', 'tumor_dna_barcode'): {'barcode': ['B00I1UL'],
                                                                          'count': 1}},
                 'other_data': {'TEST_CHAMPS1': {'histotype_acompli': '',
                                                 'histotype_acompli_other': '',
                                                 'histotype_multisarc': 'Other',
                                                 'histotype_multisarc_other': 'xxx',
                                                 'samplenature_adn': 'Frozen',
                                                 'samplenature_arn': 'Frozen',
                                                 'sex': 'Female',
                                                 'tumorcellularity_adn': '50,00%',
                                                 'tumorcellularity_arn': '100,00%',
                                                 'tumorpathologyevent_type_adn': 'Primary',
                                                 'tumorpathologyevent_type_arn': 'Primary'},
                                'TEST_CHAMPS2': {'histotype_acompli': 'Other',
                                                 'histotype_acompli_other': 'xxx',
                                                 'histotype_multisarc': '',
                                                 'histotype_multisarc_other': '',
                                                 'samplenature_adn': 'FFPE',
                                                 'samplenature_arn': 'FFPE',
                                                 'sex': 'Female',
                                                 'tumorcellularity_adn': '50,00%',
                                                 'tumorcellularity_arn': '100,00%',
                                                 'tumorpathologyevent_type_adn': 'Primary',
                                                 'tumorpathologyevent_type_arn': 'Primary'},
                                'TEST_CHAMPS3': {'histotype_acompli': '',
                                                 'histotype_acompli_other': '',
                                                 'histotype_multisarc': 'Other',
                                                 'histotype_multisarc_other': 'xxx',
                                                 'samplenature_adn': 'Frozen',
                                                 'samplenature_arn': 'Frozen',
                                                 'sex': 'Female',
                                                 'tumorcellularity_adn': '50,00%',
                                                 'tumorcellularity_arn': '100,00%',
                                                 'tumorpathologyevent_type_adn': 'Metastatic',
                                                 'tumorpathologyevent_type_arn': 'Metastatic'}}}
